### PR TITLE
Merge pull request #2 from Rodritz/main

### PR DESCRIPTION
**Pull request by Rodritz**
Merge pull request #1 from Rodritz/dev/karinameza

### CODE REVIEW

**Review by Rodritz — COMMENTED** [review]
nuevo merge de Karina

**Review by Rodritz — COMMENTED** [review]
perfecto

**Review by Rodritz — COMMENTED** [review]
perfecto

**Comment by Karinasolmeza** [comment]
a ver q pasa

**Review by Karinasolmeza — APPROVED** [review]

**Pull request merged**
